import genanki
import random

model_id = random.randrange(1 << 30, 1 << 31)
my_model = genanki.Model(
  model_id,
  'Modelo de Verbo Inglés Avanzado',
  fields=[
    {'name': 'Verbo'},
    {'name': 'Significado'},
    {'name': 'Presente'},
    {'name': 'Pasado'},
    {'name': 'Futuro'},
  ],
  templates=[
    {
      'name': 'Card 1',
      'qfmt': '<h1 style="text-align: center;">{{Verbo}}</h2>',
      'afmt': '{{FrontSide}}<br>{{Significado}}<hr id="answer"><b>Presente:</b><br>{{Presente}}<br><b>Pasado:</b><br>{{Pasado}}<br><b>Futuro:</b><br>{{Futuro}}',
    },
  ])

deck_id = random.randrange(1 << 30, 1 << 31)
my_deck = genanki.Deck(
  deck_id,
  'Verbos Comunes en Inglés: Tiempos Verbales')

verbos_con_ejemplos = [
    ('be', 'ser/estar', 
     'I am happy. / You are late. / We are here.', 
     'I was tired. / He was at school. / They were busy.', 
     'I will be there. / She will be fine. / It will be okay.'),
    ('have', 'tener', 
     'I have a question. / You have time. / They have a cat.', 
     'I had a dream. / We had lunch. / She had fun.', 
     'I will have a meeting. / He will have a chance. / We will have a break.'),
    ('do', 'hacer', 
     'I do my best. / You do the dishes. / They do their homework.', 
     'I did my workout. / She did well. / We did everything.', 
     'I will do my chores. / You will do great. / They will do it tomorrow.'),
     ('say', 'decir', 
     'I say hello. (Digo hola.) / You say goodbye. (Dices adiós.) / They say yes. (Dicen sí.)', 
     'I said sorry. (Dije lo siento.) / He said no. (Él dijo no.) / We said thanks. (Dijimos gracias.)', 
     'I will say the truth. (Diré la verdad.) / She will say nothing. (Ella no dirá nada.) / It will say error. (Dirá error.)'),
    ('go', 'ir', 
     'I go to school. (Voy a la escuela.) / You go home. (Vas a casa.) / They go to work. (Van al trabajo.)', 
     'I went to the park. (Fui al parque.) / She went to a party. (Ella fue a una fiesta.) / We went shopping. (Fuimos de compras.)', 
     'I will go on vacation. (Iré de vacaciones.) / He will go to the gym. (Él irá al gimnasio.) / They will go out. (Saldrán.)'),
    ('get', 'obtener', 
     'I get a gift. (Obtengo un regalo.) / You get a chance. (Obtienes una oportunidad.) / They get a break. (Obtienen un descanso.)', 
     'I got a letter. (Recibí una carta.) / He got the job. (Él consiguió el trabajo.) / We got lost. (Nos perdimos.)', 
     'I will get ready. (Me prepararé.) / She will get a car. (Ella conseguirá un auto.) / It will get better. (Mejorará.)'),
    ('make', 'hacer/crear',
     'I make dinner. (Hago la cena.) / You make a plan. (Haces un plan.) / They make a decision. (Toman una decisión.)',
     'I made a cake. (Hice un pastel.) / She made a call. (Ella hizo una llamada.) / We made a mistake. (Cometimos un error.)',
     'I will make an effort. (Haré un esfuerzo.) / He will make a trip. (Él hará un viaje.) / They will make a change. (Harán un cambio.)'),
    ('know', 'saber/conocer',
     'I know the answer. (Sé la respuesta.) / You know the way. (Conoces el camino.) / They know the truth. (Saben la verdad.)',
     'I knew a secret. (Sabía un secreto.) / She knew him. (Ella lo conocía.) / We knew the risks. (Conocíamos los riesgos.)',
     'I will know tomorrow. (Sabré mañana.) / He will know soon. (Él sabrá pronto.) / They will know eventually. (Eventualmente sabrán.)'),
    ('think', 'pensar',
     'I think it’s right. (Pienso que está bien.) / You think too much. (Piensas demasiado.) / They think differently. (Piensan diferente.)',
     'I thought about you. (Pensé en ti.) / She thought it was funny. (Ella pensó que era divertido.) / We thought the same. (Pensábamos lo mismo.)',
     'I will think of a solution. (Pensaré en una solución.) / He will think it over. (Él lo pensará.) / They will think about it. (Ellos lo pensarán.)'),
    ('take', 'tomar',
     'I take a shower. (Tomo una ducha.) / You take a risk. (Tomas un riesgo.) / They take a break. (Toman un descanso.)',
     'I took a picture. (Tomé una foto.) / She took a seat. (Ella tomó asiento.) / We took a walk. (Dimos un paseo.)',
     'I will take your advice. (Tomaré tu consejo.) / He will take the bus. (Él tomará el autobús.) / They will take action. (Tomarán medidas.)'),
    ('see', 'ver',
     'I see the moon. (Veo la luna.) / You see the stars. (Ves las estrellas.) / They see the ocean. (Ven el océano.)',
     'I saw a movie. (Vi una película.) / She saw a bird. (Ella vio un pájaro.) / We saw a play. (Vimos una obra.)',
     'I will see you later. (Te veré más tarde.) / He will see it soon. (Él lo verá pronto.) / They will see the results. (Verán los resultados.)'),
    ('come', 'venir',
     'I come to class. (Vengo a clase.) / You come to the party. (Vienes a la fiesta.) / They come to work. (Vienen a trabajar.)',
     'I came home late. (Llegué a casa tarde.) / She came to help. (Ella vino a ayudar.) / We came to win. (Vinimos a ganar.)',
     'I will come early. (Vendré temprano.) / He will come with us. (Él vendrá con nosotros.) / They will come to understand. (Vendrán a entender.)'),
    ('want', 'querer',
     'I want some water. (Quiero algo de agua.) / You want to leave. (Quieres irte.) / They want to play. (Quieren jugar.)',
     'I wanted to speak. (Quería hablar.) / She wanted to stay. (Ella quería quedarse.) / We wanted to try. (Queríamos intentar.)',
     'I will want to rest. (Querré descansar.) / He will want to know. (Él querrá saber.) / They will want to see. (Querrán ver.)'),
    ('look', 'mirar',
     'I look at the sky. (Miro el cielo.) / You look tired. (Te ves cansado/a.) / They look happy. (Se ven felices.)',
     'I looked for my keys. (Busqué mis llaves.) / She looked surprised. (Ella se vio sorprendida.) / We looked everywhere. (Buscamos por todas partes.)',
     'I will look into it. (Lo investigaré.) / He will look after the cat. (Él cuidará al gato.) / They will look different. (Se verán diferentes.)'),
    ('use', 'usar',
     'I use a pen. (Uso un bolígrafo.) / You use a computer. (Usas una computadora.) / They use a map. (Usan un mapa.)',
     'I used a new tool. (Usé una herramienta nueva.) / She used to smoke. (Ella solía fumar.) / We used the stairs. (Usamos las escaleras.)',
     'I will use my time wisely. (Usaré mi tiempo sabiamente.) / He will use the car. (Él usará el coche.) / They will use the opportunity. (Usarán la oportunidad.)'),
     ('find', 'encontrar',
     'I find my keys. (Encuentro mis llaves.) / You find a solution. (Encuentras una solución.) / They find happiness. (Encuentran la felicidad.)',
     'I found a coin. (Encontré una moneda.) / She found her friend. (Ella encontró a su amigo.) / We found a good restaurant. (Encontramos un buen restaurante.)',
     'I will find the answer. (Encontraré la respuesta.) / He will find a way. (Él encontrará un camino.) / They will find it interesting. (Lo encontrarán interesante.)'),
    ('give', 'dar',
     'I give a gift. (Doy un regalo.) / You give advice. (Das consejo.) / They give support. (Dan apoyo.)',
     'I gave a speech. (Di un discurso.) / She gave a hug. (Ella dio un abrazo.) / We gave our best. (Dimos lo mejor de nosotros.)',
     'I will give you a call. (Te daré una llamada.) / He will give it a try. (Él lo intentará.) / They will give us feedback. (Nos darán retroalimentación.)'),
    ('tell', 'contar',
     'I tell a story. (Cuento una historia.) / You tell the truth. (Dices la verdad.) / They tell jokes. (Cuentan chistes.)',
     'I told my name. (Dije mi nombre.) / She told a secret. (Ella contó un secreto.) / We told them everything. (Les contamos todo.)',
     'I will tell you later. (Te lo diré más tarde.) / He will tell his parents. (Él les dirá a sus padres.) / They will tell the news. (Ellos contarán las noticias.)'),
    ('try', 'intentar',
     'I try to learn. (Intento aprender.) / You try to cook. (Intentas cocinar.) / They try to win. (Intentan ganar.)',
     'I tried to call. (Intenté llamar.) / She tried to help. (Ella intentó ayudar.) / We tried to change. (Intentamos cambiar.)',
     'I will try again. (Intentaré de nuevo.) / He will try something new. (Él probará algo nuevo.) / They will try their best. (Intentarán hacer lo mejor posible.)'),
    ('ask', 'preguntar',
     'I ask a question. (Hago una pregunta.) / You ask for help. (Pides ayuda.) / They ask for directions. (Piden direcciones.)',
     'I asked his name. (Pregunté su nombre.) / She asked for a coffee. (Ella pidió un café.) / We asked about the price. (Preguntamos sobre el precio.)',
     'I will ask again. (Volveré a preguntar.) / He will ask her out. (Él la invitará a salir.) / They will ask for more. (Pedirán más.)'),
    ('need', 'necesitar',
     'I need water. (Necesito agua.) / You need sleep. (Necesitas dormir.) / They need support. (Necesitan apoyo.)',
     'I needed advice. (Necesité consejo.) / She needed time. (Ella necesitó tiempo.) / We needed money. (Necesitamos dinero.)',
     'I will need your help. (Necesitaré tu ayuda.) / He will need to decide. (Él necesitará decidir.) / They will need a car. (Necesitarán un coche.)'),
    ('feel', 'sentir',
     'I feel happy. (Me siento feliz.) / You feel cold. (Sientes frío.) / They feel excited. (Se sienten emocionados.)',
     'I felt scared. (Me sentí asustado.) / She felt alone. (Ella se sintió sola.) / We felt confident. (Nos sentimos confiados.)',
     'I will feel better. (Me sentiré mejor.) / He will feel the same. (Él se sentirá igual.) / They will feel welcome. (Se sentirán bienvenidos.)'),
    ('become', 'convertirse',
     'I become a teacher. (Me convierto en profesor.) / You become stronger. (Te vuelves más fuerte.) / They become friends. (Se vuelven amigos.)',
     'I became interested. (Me interesé.) / She became famous. (Ella se hizo famosa.) / We became tired. (Nos cansamos.)',
     'I will become an engineer. (Me convertiré en ingeniero.) / He will become a chef. (Él se convertirá en chef.) / They will become partners. (Se convertirán en socios.)'),
    ('leave', 'dejar',
     'I leave the house. (Dejo la casa.) / You leave a message. (Dejas un mensaje.) / They leave the city. (Dejan la ciudad.)',
     'I left my job. (Dejé mi trabajo.) / She left early. (Ella se fue temprano.) / We left the party. (Nos fuimos de la fiesta.)',
     'I will leave tomorrow. (Me iré mañana.) / He will leave a note. (Él dejará una nota.) / They will leave together. (Se irán juntos.)'),
    ('put', 'poner',
     'I put the book on the table. (Pongo el libro en la mesa.) / You put your shoes on. (Te pones tus zapatos.) / They put the dishes away. (Guardan los platos.)',
     'I put away my clothes. (Guardé mi ropa.) / She put up a fight. (Ella presentó pelea.) / We put off the meeting. (Posponemos la reunión.)',
     'I will put it here. (Lo pondré aquí.) / He will put together a team. (Él formará un equipo.) / They will put out a new album. (Lanzarán un nuevo álbum.)'),
    ('mean', 'significar',
     'I mean what I say. (Digo lo que quiero decir.) / You mean a lot to me. (Significas mucho para mí.) / They mean business. (Van en serio.)',
     'I meant to call you. (Tenía la intención de llamarte.) / She meant well. (Ella tenía buenas intenciones.) / We meant to arrive early. (Teníamos la intención de llegar temprano.)',
     'I will mean it this time. (Lo diré en serio esta vez.) / He will mean to do it. (Él tendrá la intención de hacerlo.) / They will mean more than words. (Significarán más que palabras.)'),
     ('keep', 'mantener',
     'I keep my room clean. (Mantengo mi habitación limpia.) / You keep the secret. (Guardas el secreto.) / They keep working. (Siguen trabajando.)',
     'I kept the receipt. (Guardé el recibo.) / She kept her promise. (Ella mantuvo su promesa.) / We kept our calm. (Mantuvimos la calma.)',
     'I will keep trying. (Seguiré intentando.) / He will keep studying. (Él seguirá estudiando.) / They will keep growing. (Seguirán creciendo.)'),
    ('let', 'permitir',
     'I let you go. (Te dejo ir.) / You let him know. (Le haces saber.) / They let us play. (Nos dejan jugar.)',
     'I let her win. (La dejé ganar.) / She let the dog out. (Ella dejó salir al perro.) / We let them decide. (Les dejamos decidir.)',
     'I will let you decide. (Te dejaré decidir.) / He will let me use his phone. (Él me permitirá usar su teléfono.) / They will let the cat in. (Dejarán entrar al gato.)'),
    ('begin', 'empezar',
     'I begin my project. (Empiezo mi proyecto.) / You begin to understand. (Comienzas a entender.) / They begin a journey. (Empiezan un viaje.)',
     'I began to read. (Empecé a leer.) / She began to cry. (Ella comenzó a llorar.) / We began to sing. (Comenzamos a cantar.)',
     'I will begin to study. (Comenzaré a estudiar.) / He will begin working. (Él comenzará a trabajar.) / They will begin to build. (Empezarán a construir.)'),
    ('seem', 'parecer',
     'I seem happy. (Parezco feliz.) / You seem tired. (Pareces cansado/a.) / They seem confused. (Parecen confundidos.)',
     'I seemed well. (Parecía estar bien.) / She seemed interested. (Ella parecía interesada.) / We seemed to agree. (Parecíamos estar de acuerdo.)',
     'I will seem different. (Pareceré diferente.) / He will seem strong. (Él parecerá fuerte.) / They will seem ready. (Parecerán listos.)'),
    ('help', 'ayudar',
     'I help my friends. (Ayudo a mis amigos.) / You help with cooking. (Ayudas con la cocina.) / They help each other. (Se ayudan el uno al otro.)',
     'I helped her study. (La ayudé a estudiar.) / She helped me move. (Ella me ayudó a mudarme.) / We helped them clean. (Les ayudamos a limpiar.)',
     'I will help you tomorrow. (Te ayudaré mañana.) / He will help fix it. (Él ayudará a arreglarlo.) / They will help us find it. (Nos ayudarán a encontrarlo.)'),
    ('talk', 'hablar',
     'I talk to my mom. (Hablo con mi mamá.) / You talk too much. (Hablas demasiado.) / They talk about sports. (Hablan sobre deportes.)',
     'I talked to the teacher. (Hablé con el profesor.) / She talked on the phone. (Ella habló por teléfono.) / We talked all night. (Hablamos toda la noche.)',
     'I will talk to you later. (Hablaré contigo más tarde.) / He will talk about his trip. (Él hablará sobre su viaje.) / They will talk to the manager. (Hablarán con el gerente.)'),
    ('turn', 'girar',
     'I turn the page. (Giro la página.) / You turn the key. (Giras la llave.) / They turn around. (Se dan la vuelta.)',
     'I turned off the light. (Apagué la luz.) / She turned down the offer. (Ella rechazó la oferta.) / We turned up late. (Llegamos tarde.)',
     'I will turn into the parking lot. (Entraré en el estacionamiento.) / He will turn the situation around. (Él revertirá la situación.) / They will turn over a new leaf. (Empezarán de nuevo.)'),
     ('start', 'comenzar',
     'I start my day early. (Comienzo mi día temprano.) / You start a new job. (Comienzas un nuevo trabajo.) / They start a project. (Comienzan un proyecto.)',
     'I started learning Spanish. (Comencé a aprender español.) / She started a company. (Ella fundó una empresa.) / We started at six. (Comenzamos a las seis.)',
     'I will start exercising. (Comenzaré a hacer ejercicio.) / He will start to cook. (Él comenzará a cocinar.) / They will start soon. (Comenzarán pronto.)'),
    ('show', 'mostrar',
     'I show my ID. (Muestro mi identificación.) / You show the way. (Muestras el camino.) / They show their work. (Muestran su trabajo.)',
     'I showed my portfolio. (Mostré mi portafolio.) / She showed her skills. (Ella mostró sus habilidades.) / We showed up on time. (Llegamos a tiempo.)',
     'I will show you the picture. (Te mostraré la foto.) / He will show improvement. (Él mostrará mejora.) / They will show the results. (Mostrarán los resultados.)'),
    ('hear', 'oír',
     'I hear music. (Oigo música.) / You hear a noise. (Oyes un ruido.) / They hear a cry. (Oyen un llanto.)',
     'I heard the news. (Oí las noticias.) / She heard a scream. (Ella oyó un grito.) / We heard it rain. (Oímos llover.)',
     'I will hear the song. (Oiré la canción.) / He will hear about this. (Él se enterará de esto.) / They will hear from me. (Recibirán noticias mías.)'),
    ('play', 'jugar',
     'I play soccer. (Juego al fútbol.) / You play the guitar. (Tocas la guitarra.) / They play games. (Juegan juegos.)',
     'I played chess. (Jugué al ajedrez.) / She played her part. (Ella desempeñó su papel.) / We played all day. (Jugamos todo el día.)',
     'I will play tennis. (Jugaré al tenis.) / He will play a role. (Él desempeñará un papel.) / They will play tomorrow. (Jugarán mañana.)'),
    ('run', 'correr',
     'I run every morning. (Corro todas las mañanas.) / You run fast. (Corres rápido.) / They run a business. (Dirigen un negocio.)',
     'I ran a marathon. (Corrí un maratón.) / She ran to catch the bus. (Ella corrió para alcanzar el autobús.) / We ran out of time. (Nos quedamos sin tiempo.)',
     'I will run for president. (Me postularé para presidente.) / He will run the meeting. (Él dirigirá la reunión.) / They will run away. (Huirán.)'),
    ('move', 'mover',
     'I move the chair. (Muevo la silla.) / You move to a new city. (Te mudas a una nueva ciudad.) / They move forward. (Avanzan.)',
     'I moved the car. (Moví el coche.) / She moved closer. (Ella se acercó más.) / We moved houses. (Nos mudamos de casa.)',
     'I will move out. (Me mudaré.) / He will move in. (Él se mudará.) / They will move up. (Ascenderán.)'),
    ('like', 'gustar',
     'I like chocolate. (Me gusta el chocolate.) / You like to dance. (Te gusta bailar.) / They like the movie. (Les gusta la película.)',
     'I liked the book. (Me gustó el libro.) / She liked the gift. (A ella le gustó el regalo.) / We liked the idea. (Nos gustó la idea.)',
     'I will like the trip. (Me gustará el viaje.) / He will like the news. (A él le gustará la noticia.) / They will like the plan. (Les gustará el plan.)'),
    ('live', 'vivir',
     'I live in Spain. (Vivo en España.) / You live well. (Vives bien.) / They live together. (Viven juntos.)',
     'I lived abroad. (Viví en el extranjero.) / She lived alone. (Ella vivió sola.) / We lived happily. (Vivimos felices.)',
     'I will live in Japan. (Viviré en Japón.) / He will live with friends. (Él vivirá con amigos.) / They will live in the city. (Vivirán en la ciudad.)'),
    ('hold', 'sostener',
     'I hold the book. (Sostengo el libro.) / You hold my hand. (Sostienes mi mano.) / They hold the key. (Sostienen la llave.)',
     'I held a meeting. (Celebré una reunión.) / She held her breath. (Ella contuvo la respiración.) / We held the line. (Mantuvimos la línea.)',
     'I will hold a party. (Organizaré una fiesta.) / He will hold onto hope. (Él se aferrará a la esperanza.) / They will hold the record. (Mantendrán el récord.)'),
     ('bring', 'traer',
     'I bring my lunch to work. (Traigo mi almuerzo al trabajo.) / You bring joy. (Tú traes alegría.) / They bring their friends. (Ellos traen a sus amigos.)',
     'I brought my umbrella. (Traje mi paraguas.) / She brought a cake. (Ella trajo un pastel.) / We brought our equipment. (Trajimos nuestro equipo.)',
     'I will bring the drinks. (Traeré las bebidas.) / He will bring the news. (Él traerá las noticias.) / They will bring the documents. (Ellos traerán los documentos.)'),
    ('happen', 'suceder',
     'I hope it happens. (Espero que suceda.) / You make it happen. (Tú haces que suceda.) / They see what happens. (Ellos ven qué sucede.)',
     'It happened yesterday. (Sucedió ayer.) / Something strange happened. (Algo extraño sucedió.) / We knew it would happen. (Sabíamos que sucedería.)',
     'It will happen soon. (Sucederá pronto.) / What will happen if...? (¿Qué sucederá si...?) / They will make it happen. (Ellos harán que suceda.)'),
    ('write', 'escribir',
     'I write a letter. (Escribo una carta.) / You write a report. (Escribes un informe.) / They write a book. (Escriben un libro.)',
     'I wrote an email. (Escribí un correo electrónico.) / She wrote a novel. (Ella escribió una novela.) / We wrote the lyrics. (Escribimos la letra.)',
     'I will write a diary. (Escribiré un diario.) / He will write an article. (Él escribirá un artículo.) / They will write a play. (Escribirán una obra de teatro.)'),
    ('provide', 'proveer',
     'I provide support. (Proporciono apoyo.) / You provide the means. (Proporcionas los medios.) / They provide services. (Ellos proveen servicios.)',
     'I provided help. (Proporcioné ayuda.) / She provided food. (Ella proporcionó comida.) / We provided information. (Proporcionamos información.)',
     'I will provide advice. (Proporcionaré consejo.) / He will provide the funds. (Él proporcionará los fondos.) / They will provide the solution. (Ellos proporcionarán la solución.)'),
    ('sit', 'sentar',
     'I sit at the desk. (Me siento en el escritorio.) / You sit down. (Te sientas.) / They sit together. (Se sientan juntos.)',
     'I sat in the chair. (Me senté en la silla.) / She sat by the window. (Ella se sentó junto a la ventana.) / We sat on the ground. (Nos sentamos en el suelo.)',
     'I will sit near you. (Me sentaré cerca de ti.) / He will sit with us. (Él se sentará con nosotros.) / They will sit in the front. (Se sentarán en la parte de adelante.)'),
    ('stand', 'estar de pie',
     'I stand in line. (Estoy de pie en la fila.) / You stand out. (Destacas.) / They stand up. (Se levantan.)',
     'I stood at the door. (Estuve de pie en la puerta.) / She stood still. (Ella se quedó quieta.) / We stood together. (Estuvimos juntos de pie.)',
     'I will stand by you. (Estaré a tu lado.) / He will stand for election. (Él se presentará a las elecciones.) / They will stand firm. (Se mantendrán firmes.)'),
    ('lose', 'perder',
     'I lose my keys. (Pierdo mis llaves.) / You lose time. (Pierdes tiempo.) / They lose the game. (Pierden el juego.)',
     'I lost my way. (Perdí el camino.) / She lost her phone. (Ella perdió su teléfono.) / We lost the match. (Perdimos el partido.)',
     'I will lose weight. (Perderé peso.) / He will lose patience. (Él perderá la paciencia.) / They will lose interest. (Perderán interés.)'),
    ('pay', 'pagar',
     'I pay the bill. (Pago la factura.) / You pay attention. (Prestas atención.) / They pay respect. (Rinden respeto.)',
     'I paid in cash. (Pagué en efectivo.) / She paid a fine. (Ella pagó una multa.) / We paid our dues. (Pagamos nuestras cuotas.)',
     'I will pay the debt. (Pagaré la deuda.) / He will pay the price. (Él pagará el precio.) / They will pay for their actions. (Pagarán por sus acciones.)'),
    ('set', 'establecer',
     'I set the table. (Pongo la mesa.) / You set goals. (Estableces metas.) / They set the rules. (Establecen las reglas.)',
     'I set an alarm. (Puse una alarma.) / She set a record. (Ella estableció un récord.) / We set a date. (Fijamos una fecha.)',
     'I will set it up. (Lo configuraré.) / He will set a trap. (Él pondrá una trampa.) / They will set the standards. (Establecerán los estándares.)'),
     ('learn', 'aprender',
     'I learn Spanish. (Aprendo español.) / You learn to play piano. (Aprendes a tocar el piano.) / They learn quickly. (Aprenden rápidamente.)',
     'I learned a new word. (Aprendí una palabra nueva.) / She learned to swim. (Ella aprendió a nadar.) / We learned the truth. (Aprendimos la verdad.)',
     'I will learn to cook. (Aprenderé a cocinar.) / He will learn the rules. (Él aprenderá las reglas.) / They will learn from mistakes. (Aprenderán de los errores.)'),
    ('change', 'cambiar',
     'I change my clothes. (Cambio mi ropa.) / You change your mind. (Cambias de opinión.) / They change the layout. (Cambian la distribución.)',
     'I changed the channel. (Cambié el canal.) / She changed her hairstyle. (Ella cambió su peinado.) / We changed our plans. (Cambiamos nuestros planes.)',
     'I will change jobs. (Cambiaré de trabajo.) / He will change it. (Él lo cambiará.) / They will change the system. (Cambiarán el sistema.)'),
    ('lead', 'liderar',
     'I lead a team. (Lidero un equipo.) / You lead by example. (Lideras con el ejemplo.) / They lead a movement. (Lideran un movimiento.)',
     'I led a project. (Lideré un proyecto.) / She led the group. (Ella lideró el grupo.) / We led the company to success. (Lideramos la empresa hacia el éxito.)',
     'I will lead a discussion. (Lideraré una discusión.) / He will lead them. (Él los liderará.) / They will lead the change. (Liderarán el cambio.)'),
    ('understand', 'entender',
     'I understand the lesson. (Entiendo la lección.) / You understand the joke. (Entiendes el chiste.) / They understand the situation. (Entienden la situación.)',
     'I understood the instructions. (Entendí las instrucciones.) / She understood the risks. (Ella entendió los riesgos.) / We understood each other. (Nos entendimos mutuamente.)',
     'I will understand more. (Entenderé más.) / He will understand soon. (Él entenderá pronto.) / They will understand the reasons. (Entenderán las razones.)'),
    ('watch', 'ver',
     'I watch TV. (Veo la televisión.) / You watch the stars. (Observas las estrellas.) / They watch a play. (Ven una obra.)',
     'I watched a movie. (Vi una película.) / She watched the sunset. (Ella vio la puesta de sol.) / We watched the game. (Vimos el partido.)',
     'I will watch the show. (Veré el espectáculo.) / He will watch over you. (Él velará por ti.) / They will watch the event. (Verán el evento.)'),
    ('follow', 'seguir',
     'I follow the path. (Sigo el camino.) / You follow the rules. (Sigues las reglas.) / They follow the leader. (Siguen al líder.)',
     'I followed the advice. (Seguí el consejo.) / She followed her heart. (Ella siguió su corazón.) / We followed the signs. (Seguimos las señales.)',
     'I will follow my dreams. (Seguiré mis sueños.) / He will follow up. (Él hará un seguimiento.) / They will follow the plan. (Seguirán el plan.)'),
    ('stop', 'detener',
     'I stop at the red light. (Me detengo en el semáforo rojo.) / You stop the music. (Detienes la música.) / They stop working. (Dejan de trabajar.)',
     'I stopped smoking. (Dejé de fumar.) / She stopped to help. (Ella se detuvo para ayudar.) / We stopped the leak. (Detuvimos la fuga.)',
     'I will stop by. (Pasaré por allí.) / He will stop them. (Él los detendrá.) / They will stop the project. (Detendrán el proyecto.)'),
    ('create', 'crear',
     'I create art. (Creo arte.) / You create a website. (Creas un sitio web.) / They create opportunities. (Crean oportunidades.)',
     'I created a song. (Creé una canción.) / She created a business. (Ella creó un negocio.) / We created a plan. (Creamos un plan.)',
     'I will create a book. (Crearé un libro.) / He will create a game. (Él creará un juego.) / They will create a community. (Crearán una comunidad.)'),
     ('speak', 'hablar',
     'I speak English. (Hablo inglés.) / You speak softly. (Hablas suavemente.) / They speak loudly. (Hablan en voz alta.)',
     'I spoke to John. (Hablé con John.) / She spoke quickly. (Ella habló rápidamente.) / We spoke about the issue. (Hablamos sobre el asunto.)',
     'I will speak to the manager. (Hablaré con el gerente.) / He will speak at the conference. (Él hablará en la conferencia.) / They will speak to each other. (Ellos hablarán entre sí.)'),
    ('read', 'leer',
     'I read a book. (Leo un libro.) / You read the news. (Lees las noticias.) / They read a sign. (Leen un cartel.)',
     'I read a novel yesterday. (Leí una novela ayer.) / She read the letter aloud. (Ella leyó la carta en voz alta.) / We read the report together. (Leímos el informe juntos.)',
     'I will read your article. (Leeré tu artículo.) / He will read more often. (Él leerá más a menudo.) / They will read the instructions. (Leerán las instrucciones.)'),
    ('allow', 'permitir',
     'I allow it. (Lo permito.) / You allow pets. (Permites mascotas.) / They allow questions. (Permiten preguntas.)',
     'I allowed him to leave early. (Permití que se fuera temprano.) / She allowed me to explain. (Ella me permitió explicar.) / We allowed them to enter. (Les permitimos entrar.)',
     'I will allow more time. (Permitiré más tiempo.) / He will allow access. (Él permitirá el acceso.) / They will allow participation. (Permitirán la participación.)'),
    ('add', 'añadir',
     'I add sugar to my coffee. (Añado azúcar a mi café.) / You add value. (Añades valor.) / They add details. (Añaden detalles.)',
     'I added salt to the recipe. (Añadí sal a la receta.) / She added a comment. (Ella añadió un comentario.) / We added a new member. (Añadimos un nuevo miembro.)',
     'I will add more information. (Añadiré más información.) / He will add a song. (Él añadirá una canción.) / They will add a chapter. (Añadirán un capítulo.)'),
    ('spend', 'gastar',
     'I spend money wisely. (Gasto dinero sabiamente.) / You spend time reading. (Pasas tiempo leyendo.) / They spend energy. (Gastan energía.)',
     'I spent my vacation in Spain. (Pasé mis vacaciones en España.) / She spent her childhood abroad. (Ella pasó su infancia en el extranjero.) / We spent the day together. (Pasamos el día juntos.)',
     'I will spend the holidays with family. (Pasaré las vacaciones con la familia.) / He will spend less. (Él gastará menos.) / They will spend the summer working. (Pasarán el verano trabajando.)'),
    ('grow', 'crecer',
     'I grow vegetables in my garden. (Cultivo vegetales en mi jardín.) / You grow taller. (Crecen más alto.) / They grow impatient. (Se impacientan.)',
     'I grew up in the city. (Crecí en la ciudad.) / She grew her business. (Ella expandió su negocio.) / We grew closer. (Nos acercamos más.)',
     'I will grow my hair long. (Dejaré crecer mi cabello largo.) / He will grow stronger. (Él se volverá más fuerte.) / They will grow their network. (Ellos ampliarán su red.)'),
    ('open', 'abrir',
     'I open the door. (Abro la puerta.) / You open a bank account. (Abres una cuenta bancaria.) / They open a store. (Abren una tienda.)',
     'I opened a gift. (Abrí un regalo.) / She opened her heart. (Ella abrió su corazón.) / We opened a bottle of wine. (Abrimos una botella de vino.)',
     'I will open a new chapter. (Abriré un nuevo capítulo.) / He will open the meeting. (Él abrirá la reunión.) / They will open the ceremony. (Ellos inaugurarán la ceremonia.)'),
    ('walk', 'caminar',
     'I walk to school. (Camino a la escuela.) / You walk the dog. (Paseas al perro.) / They walk for exercise. (Caminan para ejercitarse.)',
     'I walked in the park. (Caminé en el parque.) / She walked away. (Ella se alejó caminando.) / We walked home together. (Caminamos a casa juntos.)',
     'I will walk faster. (Caminaré más rápido.) / He will walk her home. (Él la acompañará a casa caminando.) / They will walk the entire city. (Caminarán toda la ciudad.)'),
     ('win', 'ganar',
     'I win the game. (Gano el juego.) / You win the prize. (Ganas el premio.) / They win the competition. (Ganan la competencia.)',
     'I won a trophy. (Gané un trofeo.) / She won the lottery. (Ella ganó la lotería.) / We won the match. (Ganamos el partido.)',
     'I will win the race. (Ganaré la carrera.) / He will win her heart. (Él ganará su corazón.) / They will win the award. (Ganarán el premio.)'),
    ('offer', 'ofrecer',
     'I offer help. (Ofrezco ayuda.) / You offer advice. (Ofreces consejo.) / They offer a discount. (Ofrecen un descuento.)',
     'I offered my seat. (Ofrecí mi asiento.) / She offered a solution. (Ella ofreció una solución.) / We offered our services. (Ofrecimos nuestros servicios.)',
     'I will offer my expertise. (Ofreceré mi experiencia.) / He will offer support. (Él ofrecerá apoyo.) / They will offer more options. (Ofrecerán más opciones.)'),
    ('remember', 'recordar',
     'I remember your name. (Recuerdo tu nombre.) / You remember the way. (Recuerdas el camino.) / They remember the story. (Recuerdan la historia.)',
     'I remembered the event. (Recordé el evento.) / She remembered his face. (Ella recordó su rostro.) / We remembered the password. (Recordamos la contraseña.)',
     'I will remember the date. (Recordaré la fecha.) / He will remember to call. (Él recordará llamar.) / They will remember the advice. (Recordarán el consejo.)'),
    ('love', 'amar',
     'I love my family. (Amo a mi familia.) / You love to travel. (Te encanta viajar.) / They love music. (Les encanta la música.)',
     'I loved the concert. (Me encantó el concierto.) / She loved the gift. (A ella le encantó el regalo.) / We loved the movie. (Nos encantó la película.)',
     'I will love the experience. (Me encantará la experiencia.) / He will love the surprise. (Le encantará la sorpresa.) / They will love the place. (Les encantará el lugar.)'),
    ('consider', 'considerar',
     'I consider your opinion. (Considero tu opinión.) / You consider moving. (Consideras mudarte.) / They consider all options. (Consideran todas las opciones.)',
     'I considered the proposal. (Consideré la propuesta.) / She considered her choices. (Ella consideró sus opciones.) / We considered it carefully. (Lo consideramos cuidadosamente.)',
     'I will consider your suggestion. (Consideraré tu sugerencia.) / He will consider the consequences. (Él considerará las consecuencias.) / They will consider the future. (Considerarán el futuro.)'),
    ('appear', 'aparecer',
     'I appear on TV. (Aparezco en la televisión.) / You appear happy. (Pareces feliz.) / They appear confused. (Parecen confundidos.)',
     'I appeared in a play. (Aparecí en una obra de teatro.) / She appeared late. (Ella apareció tarde.) / We appeared at the event. (Aparecimos en el evento.)',
     'I will appear in court. (Apareceré en el tribunal.) / He will appear soon. (Él aparecerá pronto.) / They will appear on the list. (Aparecerán en la lista.)'),
    ('buy', 'comprar',
     'I buy groceries. (Compro víveres.) / You buy online. (Compras en línea.) / They buy a car. (Compran un coche.)',
     'I bought a house. (Compré una casa.) / She bought a dress. (Ella compró un vestido.) / We bought tickets. (Compramos boletos.)',
     'I will buy a gift. (Compraré un regalo.) / He will buy the company. (Él comprará la empresa.) / They will buy new equipment. (Comprarán equipo nuevo.)'),
    ('wait', 'esperar',
     'I wait for the bus. (Espero el autobús.) / You wait for a call. (Esperas una llamada.) / They wait for the right moment. (Esperan el momento adecuado.)',
     'I waited in line. (Esperé en la fila.) / She waited for hours. (Ella esperó durante horas.) / We waited patiently. (Esperamos pacientemente.)',
     'I will wait for you. (Te esperaré.) / He will wait until tomorrow. (Él esperará hasta mañana.) / They will wait for the news. (Esperarán las noticias.)'),
    ('serve', 'servir',
     'I serve customers. (Sirvo a los clientes.) / You serve the country. (Sirves al país.) / They serve dinner. (Sirven la cena.)',
     'I served in the army. (Serví en el ejército.) / She served drinks. (Ella sirvió bebidas.) / We served the community. (Servimos a la comunidad.)',
     'I will serve on the committee. (Serviré en el comité.) / He will serve the meal. (Él servirá la comida.) / They will serve justice. (Servirán justicia.)'),
    ('die', 'morir',
     'I die for chocolate. (Muero por el chocolate.) / You die of laughter. (Mueres de risa.) / They die of old age. (Mueren de vejez.)',
     'I died in the game. (Morí en el juego.) / She died peacefully. (Ella murió pacíficamente.) / We died of embarrassment. (Morimos de vergüenza.)',
     'I will die happy. (Moriré feliz.) / He will die a hero. (Él morirá como un héroe.) / They will die for their beliefs. (Morirán por sus creencias.)'),
     ('send', 'enviar',
     'I send emails. (Envío correos electrónicos.) / You send a message. (Envías un mensaje.) / They send gifts. (Envían regalos.)',
     'I sent a letter. (Envié una carta.) / She sent a package. (Ella envió un paquete.) / We sent invitations. (Enviamos invitaciones.)',
     'I will send a reminder. (Enviaré un recordatorio.) / He will send flowers. (Él enviará flores.) / They will send a proposal. (Enviarán una propuesta.)'),
    ('expect', 'esperar',
     'I expect good news. (Espero buenas noticias.) / You expect a call. (Esperas una llamada.) / They expect a decision. (Ellos esperan una decisión.)',
     'I expected a surprise. (Esperaba una sorpresa.) / She expected an answer. (Ella esperaba una respuesta.) / We expected a delay. (Esperábamos un retraso.)',
     'I will expect progress. (Esperaré progreso.) / He will expect feedback. (Él esperará retroalimentación.) / They will expect changes. (Esperarán cambios.)'),
    ('build', 'construir',
     'I build houses. (Construyo casas.) / You build bridges. (Construyes puentes.) / They build skyscrapers. (Construyen rascacielos.)',
     'I built a model. (Construí un modelo.) / She built a sandcastle. (Ella construyó un castillo de arena.) / We built a foundation. (Construimos una base.)',
     'I will build a website. (Construiré un sitio web.) / He will build a career. (Él construirá una carrera.) / They will build relationships. (Construirán relaciones.)'),
    ('stay', 'quedarse',
     'I stay at home. (Me quedo en casa.) / You stay with friends. (Te quedas con amigos.) / They stay in the city. (Ellos se quedan en la ciudad.)',
     'I stayed at the hotel. (Me quedé en el hotel.) / She stayed for the event. (Ella se quedó para el evento.) / We stayed longer. (Nos quedamos más tiempo.)',
     'I will stay for the weekend. (Me quedaré durante el fin de semana.) / He will stay late. (Él se quedará hasta tarde.) / They will stay focused. (Se quedarán concentrados.)'),
    ('fall', 'caer',
     'I fall on the ice. (Caigo en el hielo.) / You fall from the tree. (Caes del árbol.) / They fall in love. (Ellos se enamoran.)',
     'I fell on the stairs. (Caí en las escaleras.) / She fell off the bike. (Ella cayó de la bicicleta.) / We fell for the trick. (Caímos en la trampa.)',
     'I will fall asleep. (Me dormiré.) / He will fall behind. (Él se retrasará.) / They will fall into place. (Caerán en su lugar.)'),
    ('cut', 'cortar',
     'I cut vegetables. (Corto verduras.) / You cut paper. (Cortas papel.) / They cut hair. (Cortan cabello.)',
     'I cut a cake. (Corté un pastel.) / She cut her hair. (Ella se cortó el pelo.) / We cut the grass. (Cortamos el césped.)',
     'I will cut a deal. (Cortaré un trato.) / He will cut expenses. (Él recortará gastos.) / They will cut ties. (Cortarán lazos.)'),
    ('reach', 'alcanzar',
     'I reach the top shelf. (Alcanzo el estante superior.) / You reach a milestone. (Alcanzas un hito.) / They reach their goals. (Ellos alcanzan sus metas.)',
     'I reached the finish line. (Alcanzé la línea de meta.) / She reached for the stars. (Ella se esforzó por alcanzar las estrellas.) / We reached a compromise. (Alcanzamos un compromiso.)',
     'I will reach out to you. (Me pondré en contacto contigo.) / He will reach new heights. (Él alcanzará nuevas alturas.) / They will reach a decision. (Alcanzarán una decisión.)'),
    ('kill', 'matar',
     'I kill insects. (Mato insectos.) / You kill time. (Matas el tiempo.) / They kill boredom. (Ellos matan el aburrimiento.)',
     'I killed a spider. (Maté una araña.) / She killed the mood. (Ella mató el ambiente.) / We killed the competition. (Matamos la competencia.)',
     'I will kill the lights. (Apagaré las luces.) / He will kill the rumor. (Él desmentirá el rumor.) / They will kill the noise. (Acabarán con el ruido.)'),
    ('remain', 'permanecer',
     'I remain calm. (Permanezco tranquilo.) / You remain silent. (Permaneces en silencio.) / They remain hopeful. (Ellos permanecen esperanzados.)',
     'I remained at home. (Permanecí en casa.) / She remained focused. (Ella permaneció concentrada.) / We remained friends. (Permanecimos amigos.)',
     'I will remain patient. (Permaneceré paciente.) / He will remain committed. (Él permanecerá comprometido.) / They will remain in touch. (Permanecerán en contacto.)'),
    # Añade más verbos y ejemplos aquí
]
verbos = [
    ('be', 'ser/estar'),
    ('have', 'tener'),
    ('do', 'hacer'),
    ('say', 'decir'),
    ('go', 'ir'),
    ('get', 'obtener'),
    ('make', 'hacer/crear'),
    ('know', 'saber/conocer'),
    ('think', 'pensar'),
    ('take', 'tomar'),
    ('see', 'ver'),
    ('come', 'venir'),
    ('want', 'querer'),
    ('look', 'mirar'),
    ('use', 'usar'),
    ('find', 'encontrar'),
    ('give', 'dar'),
    ('tell', 'contar'),
    ('work', 'trabajar'),
    ('call', 'llamar'),
    ('try', 'intentar'),
    ('ask', 'preguntar'),
    ('need', 'necesitar'),
    ('feel', 'sentir'),
    ('become', 'convertirse'),
    ('leave', 'dejar'),
    ('put', 'poner'),
    ('mean', 'significar'),
    ('keep', 'mantener'),
    ('let', 'permitir'),
    ('begin', 'empezar'),
    ('seem', 'parecer'),
    ('help', 'ayudar'),
    ('talk', 'hablar'),
    ('turn', 'girar'),
    ('start', 'comenzar'),
    ('show', 'mostrar'),
    ('hear', 'oír'),
    ('play', 'jugar'),
    ('run', 'correr'),
    ('move', 'mover'),
    ('like', 'gustar'),
    ('live', 'vivir'),
    ('believe', 'creer'),
    ('hold', 'sostener'),
    ('bring', 'traer'),
    ('happen', 'suceder'),
    ('write', 'escribir'),
    ('provide', 'proveer'),
    ('sit', 'sentar'),
    ('stand', 'estar de pie'),
    ('lose', 'perder'),
    ('pay', 'pagar'),
    ('meet', 'encontrar/reunirse'),
    ('include', 'incluir'),
    ('continue', 'continuar'),
    ('set', 'establecer'),
    ('learn', 'aprender'),
    ('change', 'cambiar'),
    ('lead', 'liderar'),
    ('understand', 'entender'),
    ('watch', 'ver'),
    ('follow', 'seguir'),
    ('stop', 'detener'),
    ('create', 'crear'),
    ('speak', 'hablar'),
    ('read', 'leer'),
    ('allow', 'permitir'),
    ('add', 'añadir'),
    ('spend', 'gastar'),
    ('grow', 'crecer'),
    ('open', 'abrir'),
    ('walk', 'caminar'),
    ('win', 'ganar'),
    ('offer', 'ofrecer'),
    ('remember', 'recordar'),
    ('love', 'amar'),
    ('consider', 'considerar'),
    ('appear', 'aparecer'),
    ('buy', 'comprar'),
    ('wait', 'esperar'),
    ('serve', 'servir'),
    ('die', 'morir'),
    ('send', 'enviar'),
    ('expect', 'esperar'),
    ('build', 'construir'),
    ('stay', 'quedarse'),
    ('fall', 'caer'),
    ('cut', 'cortar'),
    ('reach', 'alcanzar'),
    ('kill', 'matar'),
    ('remain', 'permanecer'),
]

for verbo, significado, presente, pasado, futuro in verbos_con_ejemplos:
    note = genanki.Note(
        model=my_model,
        fields=[verbo, significado, presente, pasado, futuro])
    my_deck.add_note(note)

genanki.Package(my_deck).write_to_file('verbos_comunes_ingles_tiempos_verbales.apkg')
